# Use the latest image available.
image: Visual Studio 2017
version: 0.1.{build}

install:
  # Install Rust through rustup
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -y --default-toolchain 1.30.0 --default-host i686-pc-windows-msvc
  # Add to path
  - set PATH=%USERPROFILE%/.cargo/bin;%PATH%
  # Print the installed versions
  - rustc -vV
  - cargo -vV

build_script:
  - cargo build --1.29.0 --target i686-pc-windows-msvc

# Save the built DLL.
artifacts:
- path: target\i686-pc-windows-msvc\release\d3d9.dll
  name: D3D9

cache:
  - target
  - C:\Users\appveyor\.cargo\
  - C:\Users\appveyor\.rustup\
